Shell into master (#6)
* fix cmdline option

* adds in shell script

* adds in shell file

* switches to uberjar for dependency packaging

* fixes submit

* reverts extraneous commits

* fixes some issues

diff --git a/bin/gnocchi-submit b/bin/gnocchi-submit
--- a/bin/gnocchi-submit
+++ b/bin/gnocchi-submit
@@ -17,6 +17,8 @@
 # limitations under the License.
 #
 
+# usage: adam-submit [<spark-args> --] <adam-args>
+
 set -e
 
 # Split args into Spark and GNOCCHI args
@@ -25,46 +27,73 @@ PRE_DD=()
 POST_DD=()
 for ARG in "$@"; do
   shift
-  # echo $ARG
   if [[ $ARG == "--" ]]; then
     DD=True
     POST_DD=( "$@" )
-    echo $POST_DD
     break
   fi
   PRE_DD+=("$ARG")
 done
 
 if [[ $DD == True ]]; then
-  SPARK_ARGS="${PRE_DD[@]}"
-  GNOCCHI_ARGS="${POST_DD[@]}"
+  SPARK_ARGS=("${PRE_DD[@]}")
+  GNOCCHI_ARGS=("${POST_DD[@]}")
 else
   SPARK_ARGS=()
-  GNOCCHI_ARGS="${PRE_DD[@]}"
+  GNOCCHI_ARGS=("${PRE_DD[@]}")
 fi
 
 # does the user have GNOCCHI_OPTS set? if yes, then warn
 if [[ $DD == False && -n "$GNOCCHI_OPTS" ]]; then
     echo "WARNING: Passing Spark arguments via GNOCCHI_OPTS was recently removed."
-    echo "Run gnocchi-submit instead as gnocchi-submit <spark-args> -- <gnocchi-args>"
+    echo "Run adam-submit instead as adam-submit <spark-args> -- <adam-args>"
 fi
 
-# Figure out where GNOCCHI is installed
-SCRIPT_DIR="$(cd `dirname $0`/..; pwd)"
+# Find original directory of this script, resolving symlinks
+# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in/246128#246128
+SOURCE="${BASH_SOURCE[0]}"
+while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
+    SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+    SOURCE="$(readlink "$SOURCE")"
+    [[ $SOURCE != /* ]] && SOURCE="$SCRIPT_DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
+done
+SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
+INSTALL_DIR="$SCRIPT_DIR/.."
 
-# Get list of required jars for GNOCCHI
-GNOCCHI_JARS=$("$SCRIPT_DIR"/bin/compute-gnocchi-jars.sh)
+# Find GNOCCHI cli assembly jar
+GNOCCHI_CLI_JAR=
+if [ -d "$INSTALL_DIR/repo" ]; then
+  ASSEMBLY_DIR="$INSTALL_DIR/repo"
+else
+  ASSEMBLY_DIR="$INSTALL_DIR/gnocchi-cli/target"
+fi
 
-# Split out the CLI jar, since it will be passed to Spark as the "primary resource".
-GNOCCHI_CLI_JAR=${GNOCCHI_JARS##*,}
-GNOCCHI_JARS=$(echo "$GNOCCHI_JARS" | rev | cut -d',' -f2- | rev)
+num_jars="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi[0-9A-Za-z\.\_\-]*\.jar$" | grep -v javadoc | grep -v sources | wc -l)"
+if [ "$num_jars" -eq "0" ]; then
+  echo "Failed to find GNOCCHI cli assembly in $ASSEMBLY_DIR." 1>&2
+  echo "You need to build GNOCCHI before running this program." 1>&2
+  exit 1
+fi
 
-# append GNOCCHI_JARS to the --jars option, if any
-SPARK_ARGS=$("$SCRIPT_DIR"/bin/append_to_option.py , --jars $GNOCCHI_JARS $SPARK_ARGS)
+ASSEMBLY_JARS="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi[0-9A-Za-z\.\_\-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
+if [ "$num_jars" -gt "1" ]; then
+  echo "Found multiple GNOCCHI cli assembly jars in $ASSEMBLY_DIR:" 1>&2
+  echo "$ASSEMBLY_JARS" 1>&2
+  echo "Please remove all but one jar." 1>&2
+  exit 1
+fi
+
+GNOCCHI_CLI_JAR="${ASSEMBLY_DIR}/${ASSEMBLY_JARS}"
+
+# Allow main class to be overridden
+if [ -z "$GNOCCHI_MAIN" ]; then
+  GNOCCHI_MAIN="net.fnothaft.gnocchi.cli.GnocchiMain"
+fi
+echo "Using GNOCCHI_MAIN=$GNOCCHI_MAIN"
 
 # Find spark-submit script
 if [ -z "$SPARK_HOME" ]; then
-  SPARK_SUBMIT=$(which spark-submit)
+  SPARK_SUBMIT=$(which spark-submit || echo)
 else
   SPARK_SUBMIT="$SPARK_HOME"/bin/spark-submit
 fi
@@ -76,14 +105,9 @@ echo "Using SPARK_SUBMIT=$SPARK_SUBMIT"
 
 # submit the job to Spark
 "$SPARK_SUBMIT" \
-  --class net.fnothaft.gnocchi.cli.GnocchiMain \
+  --class $GNOCCHI_MAIN \
   --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
   --conf spark.kryo.registrator=org.bdgenomics.adam.serialization.ADAMKryoRegistrator \
-  --conf spark.kryo.registrationRequired=false \
-  $SPARK_ARGS \
-  $GNOCCHI_CLI_JAR \
-  $GNOCCHI_ARGS
-echo "Done submiting the args to GnochiMain.main()"
-  # org.bdgenomics.adam.serialization.ADAMKryoRegistrator
-  # This was the old one. net.fnothaft.gnocchi.GnocchiKryoRegistrator
-  # org.bdgenomics.adam.AdamKryoRegistrator
+  "${SPARK_ARGS[@]}" \
+  "$GNOCCHI_CLI_JAR" \
+  "${GNOCCHI_ARGS[@]}"
